### ISSUE TITLE
review treatment of ties in all calculations

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#132]
hi, (cc @guilhermejacob) i think anywhere that `incvar >=` or `incvar <=` gets used, it might be worth reviewing how ties get treated? svyiqalpha, svyisq, svyarpt, svyarpr, svyrmir, svypoormed, svylorenz all use this at some point, but it might be worth just reviewing all functions for this.  there's some discussion of ties here: https://github.com/DjalmaPessoa/convey/issues/69  and i use `svyzenga` in the example below to show how little the tie in the example _should_ affect the SE values? (if ties are handled properly, the SE should have almost no difference).  i think this issue is low-priority but _should_ be eventually fixed.  some government social programs pay a fixed amount, so it's conceivable that an analyst using our software would subset to a population where the ties actually make a difference.  also, there are going to be _many_ ties at a nation's minimum wage.  thanks djalma

```
library(survey)
library(convey)

# only difference: 3rd value is a tie or not
x_with_tie <- data.frame( income = c( 1000 , 2000 , 2000 , 3000 ) , weight = c( 1 , 10 , 10 , 1 ) )
x_no_tie <- data.frame( income = c( 1000 , 2000 , 2001 , 3000 ) , weight = c( 1 , 10 , 10 , 1 ) )


y_with_tie <- svydesign( ~ 1 , data = x_with_tie , weights = ~ weight )
y_with_tie <- convey_prep( y_with_tie )
y_no_tie <- svydesign( ~ 1 , data = x_no_tie , weights = ~ weight )
y_no_tie <- convey_prep( y_no_tie )


# big differences in the SE
SE( svyarpt( ~ income , y_no_tie ) )
SE( svyarpt( ~ income , y_with_tie ) )


# tiny difference in the SE
SE( svyzenga( ~ income , y_with_tie ) )
SE( svyzenga( ~ income , y_no_tie ) )



#41% difference for svyarpt.. 0.03% difference for svyzenga
( SE( svyarpt( ~ income , y_no_tie ) ) - SE( svyarpt( ~ income , y_with_tie ) ) ) / SE( svyarpt( ~ income , y_with_tie ) )
( SE( svyzenga( ~ income , y_no_tie ) ) - SE( svyzenga( ~ income , y_with_tie ) ) ) / SE( svyzenga( ~ income , y_with_tie ) )
```

**Comment by DjalmaPessoa** [comment]
If we compute the se of the arpt directly from the library survey we get:

(.6 *SE(svyquantile(~income, y_no_tie, quantile=.6, ci=TRUE))-.6 * SE(svyquantile(~income, y_with_tie, quantile=.6, ci=TRUE)))/ (.6 * SE(svyquantile(~income, y_with_tie, quantile=.6, ci=TRUE)))

that is even worse!

**Comment by DjalmaPessoa** [comment]
the problem with estimating the se  from data with ties, in convey,  is related to the linearization of quantiles using influence functions. I wasn't able to find a good reference on that, and it seems to be a hard problem to solve. I think  we will not be able to get a reasonable solution for it in a short term. I suggest we postpone this issue for other version of the library.

**Comment by ajdamico** [comment]
fine with me..  `0.3.0` now

**Comment by ajdamico** [comment]
hi, i think we still want to look at this next version?  just not right away..

**Comment by DjalmaPessoa** [comment]
Sorry, I meant just to close for this version and reopen later on

**Comment by ajdamico** [comment]
thanks, i changed the milestone

**Comment by guilhermejacob** [comment]
This is a hard one. It should not be a problem in practice, but it might show up in threshold like the minimum wage. If the analyst uses income per capita, this should be less problematic, also.

It is important to notice that all these methods rely on asymptotics. So if this is a problem, the analyst should really think about whether he has enough sample size. 

Another possibility would be to use smoothing, but it might be overkill.

**Comment by ajdamico** [comment]
like you say, mostly theoretical -- i don't think this is worth resolving but re-open if you disagree?
