### ISSUE TITLE
To compare results from survey.design and svyrep.design for the PNAD microdata

### ISSUE THREAD

**Issue by DjalmaPessoa** [ajdamico/convey#143]
In line with the comparison exercises that we have been doing it would be interesting to use the PNAD microdata to this end. The problem is the size of  microdata when using svyrep.design. Perhaps, we could work with just the microdata for a state.

**Comment by DjalmaPessoa** [comment]
can we define a database-backed svrepdesign object for the pnad2011?

**Comment by ajdamico** [comment]
you could copy the censo strategy?
https://github.com/ajdamico/asdfree/blob/master/Censo%20Demografico/download%20and%20import.R#L414-L432

**Comment by DjalmaPessoa** [comment]
is this really relevant for the version 2.0 of convey?

**Comment by ajdamico** [comment]
hi, i think this belongs in the textbook so it's not really critical to finish before cran submission.  you could change the milestone to `0.3.0` if you like?
