### ISSUE TITLE
consider acquiring EU-SILC data to match published Osier paper

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#145]
the application seems like a pain
http://ec.europa.eu/eurostat/documents/203647/771732/How_to_apply_for_microdata_access.pdf

but it would be good to match so many of the published numbers..
https://ojs.ub.uni-konstanz.de/srm/article/view/369/3494

i might be able to apply for access through CWI, but are there any easier ways?  what do you think?

**Comment by ajdamico** [comment]
check whether vardpoor's eusilc or some other public extract has enough of what you need?

**Comment by DjalmaPessoa** [comment]
To replicate the estimates in Osier's paper it would be needed much more
data than the data set eusilc in vardpoor. But I think it would be an
interesting exercise to try to matches the estimates in the paper.

I believe that it would no be difficult to the  EU_SILC data for someone
working at an institution like IBGE. Nowdays  I'm retired and probably
would not  be entitled.

I'm going to inquire about easier way of getting the data.

**Comment by guilhermejacob** [comment]
Can we contact Osier? Maybe it would be easier.

**Comment by ajdamico** [comment]
that's a good idea..

**Comment by DjalmaPessoa** [comment]
I think , by contract, he is not allowed to give the data

**Comment by guilhermejacob** [comment]
Yes. But considering that we need a subset of the original data, it might be possible.

**Comment by ajdamico** [comment]
i'll write up a draft and send it around.  we'll mention that if he can't help us access the data, that perhaps i could get it through cwi or guilherme could get it through unicef

**Comment by DjalmaPessoa** [comment]
Pedro Silva (ENCE/IBGE)  is willing to help us and will apply to have access to the data.

**Comment by ajdamico** [comment]
that's kind of him.  i think either i or guilherme should be able to
acquire it through our own institutional affiliations, but it would be good
to go through him if applying ourselves doesn't work for some reason

**Comment by ajdamico** [comment]
@DjalmaPessoa @guilhermejacob could you review and make edits to this wiki page?  this is the letter to dr. osier that we discussed..

https://github.com/DjalmaPessoa/convey/wiki/letter-to-dr.-osier

**Comment by DjalmaPessoa** [comment]
I'm sending a document from the EU-SILC site on how to apply for data.
Apparently we have to be very specific about the desired data and has to
envolve the name of a researcher from the authorized institution.

**Comment by ajdamico** [comment]
we should still e-mail dr. osier, right?

**Comment by DjalmaPessoa** [comment]
I think so.  The  expected time to get the data is 8 weeks. If he is kind
enough to give us the data, it might be worthwhile.

**Comment by DjalmaPessoa** [comment]
We're going to have to fill the enclosed form out

**Comment by DjalmaPessoa** [comment]
It is not clear which income variable is used in Tables 2-6 of Osier's
paper.

In the convey examples we have used the eqIncome
which is defined as a slightly simplified version of the equivalized
household income? whatever that means!

In the Research application form we need to state the variables requested.

**Comment by DjalmaPessoa** [comment]
I've already started to fill out the required form. Could you please add
some itens.

**Comment by ajdamico** [comment]
could you edit the letter to dr. osier so that we ask him each of the
questions that you need answers to?  thanks

https://github.com/DjalmaPessoa/convey/wiki/letter-to-dr.-osier

**Comment by DjalmaPessoa** [comment]
Please check if the added sentence made our questions clear.

**Comment by ajdamico** [comment]
thanks..i edited it a bit

**Comment by DjalmaPessoa** [comment]
awesome.

**Comment by ajdamico** [comment]
@guilhermejacob do you have any edits?  if not, @DjalmaPessoa do you want to send the e-mail to osier and cc us both?

**Comment by DjalmaPessoa** [comment]
Would you please send it? Thanks a lot.

**Comment by guilhermejacob** [comment]
I think it is fine. Who will send it?

**Comment by ajdamico** [comment]
sent!  so from here we'll submit the application and, after that, attempt to replicate the estimates :)

**Comment by guilhermejacob** [comment]
In case you're interested, [this post](http://muuankarski.github.io/r.eusilc/vignettes/r.eusilc_tutorial.html) shows how to get the data **since 2005** using R.
