### ISSUE TITLE
estimate the difference of indicators for different times

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#148]
_the problem is to estimate the variance of the difference since there a covariance term to be included.  
For instance, that if we consider two PNADs, in the same decade,  they keep the same strata,  so there is a covariance term to be considered when estimating the variance of the difference._

**Comment by guilhermejacob** [comment]
I think [Goga's presentation](http://www-1.ms.ut.ee/samp2008/Presentations/CGoga_influence.pdf) discusses in page 26, using [partial influence functions](https://www.math.tecnico.ulisboa.pt/~apires/PDFs/APJB_JMVA01.pdf).
[Goga, Deville and Ruiz-Gazen](http://www.jstor.org/stable/27798857) extended the Deville (2000) method to two sample estimator. @DjalmaPessoa, do you agree?

**Comment by DjalmaPessoa** [comment]
Guilherme,

I agree they extended Deville method for estimator based on two sample.

The difficulty of using two PNAD versions has nothing to do with influence
functions.

There exists even for linear estimates, where no linearization issue
involved.

It consists in taking correctly into account the overlap between two PNADs
two compute the covariance term.

At IBGE, they do some guessing and are not entirely  convincing about that.

**Comment by guilhermejacob** [comment]
I see. They use the method to analyze the difference of Gini indices over time using overlapping samples. Might not be the case for annual PNAD, but it can be useful for Continuous PNAD, don't you think?

**Comment by DjalmaPessoa** [comment]
For the time being, they don't know how to do for PNADC.  PNADC has a
rotating panel design. But they are trying to figure out the way to do it.
I'll get in touch with the PNADC manager to get the relevant information.

**Comment by guilhermejacob** [comment]
<del>Osier in disguise</del> Eurostat (2013) also proposes a method to estimate the variance of a change based in overlapping samples. In p.15, he adds:
>Please note that for most countries the correlation is zero if two estimates are compared with more than 4 years difference (the two samples do not contain the same respondents in this case and can be considered independent). *However, in some countries (e.g. Belgium) the primary sampling units have been selected for the entire duration of EU-SILC and rotation is implemented only at the within PSU level. As a consequence, also when all households are rotated out, there still remains some correlation that has to be estimated*.

I think this can be useful for strata correlation across time, too.
Here's the (very interesting) document:
[KS-RA-13-024-EN.PDF.pdf](https://github.com/DjalmaPessoa/convey/files/582092/KS-RA-13-024-EN.PDF.pdf)

**Comment by DjalmaPessoa** [comment]
Guilherme,

I agree the document you mentioned is very interesting. I've already read.
I'd like to make some remarks on using it to IBGE data using this
methodology.
Among the IBGE surveys analyzed at asdfree, there are using rotating
samples: PME and PNADC.

One advantage of using rotating sample is the possibility of producing
 longitudinal studies.

In all IBGE publications analyzing PME all results are from  cross-section
studies. The reason is simple: it is not possible to match households and
 people in different rounds of the survey. There is no household or people
key code to match units. For this reason IBGE is not able to use the data
for longitudinal studies. Of course, they would know how to do it if they
had the necessary information.  There were some efforts to circumvent the
problem using record linkage techniques.

For the PNADC they have this key code to identify household and people in
the different survey rounds.
But, as far as know, for confidentiality reasons, this key code is not
available for public use.

It might be possible, under special conditions, like academic studies to
sign some agreement with IBGE and have access to this type of data, though
I'm no sure this is the case.

**Comment by DjalmaPessoa** [comment]
Independently of what we can do with IBGE microdata, I believe the library convey should consider the possibility of comparing results for different years. This is done by the library vardpoor.  I suggest we implement at least what they do there.

**Comment by guilhermejacob** [comment]
I did some research about what `vardpoor` does to estimate net change across times with rotating samples. The approach used follows [Berger (2012)](http://sondages2012.ensai.fr/wp-content/uploads/2011/01/Berger_Rennes_2012.pdf), where variances are calculated using each round but the covariance is a result of [multivariate regression](https://github.com/CSBLatvia/vardpoor/blob/63639afd1ba046077499340779474c011a237b4f/vardpoor/R/vardcros.R#L563-L658), which allows us to calculate the variance of the difference between time periods.
I don't think it works for PNAD, but I'm quite sure it works for PNADC. Even with calibration.
Do you think we can start working on this?

**Comment by DjalmaPessoa** [comment]
This issue is much too complicated to have some solution in the near future. Before working on this,  I'd like to consult people at IBGE to see how they are going to approach it for PNADC. 
Shall we move this to milestone 3.0?

**Comment by ajdamico** [comment]
moved

**Comment by guilhermejacob** [comment]
@DjalmaPessoa , I found a SAS code by Osier to calculate net changes using the LFS survey, which shares some characteristics with PNADC. Here's the [main article](https://circabc.europa.eu/webdav/CircaBC/ESTAT/labmarstatwg/Library/statistics_working/2015/2.%207-8%20December%20(Section%20A_%20LFS)/2.%20Documents/Doc%2029%20Item%204.1%20Annex%20II.pdf) and [pdf with the code](https://circabc.europa.eu/webdav/CircaBC/ESTAT/labmarstatwg/Library/statistics_working/2015/2.%207-8%20December%20(Section%20A_%20LFS)/2.%20Documents/Doc%2029%20Item%204.1%20Annex%20II%20SAS%20programs%20explanation.pdf).

**Comment by DjalmaPessoa** [comment]
thanks

**Comment by guilhermejacob** [comment]
What is stopping us? 

1. As mentioned the influence function in `survey` and `convey` do not coincide. But that is an easy fix: apply the survey weights to `convey`'s influence function and you'll have the `survey` influence function! Why? Check inside the code for the new `svyby.survey.design2`.
1. The treatment of the `full_design` object in  `svyrecvar` inside `svyby`. I haven't found a good solution for this yet.
