### ISSUE TITLE
Multidimensional poverty: Alkire-Foster Method

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#149]
Maybe we can implement a function to estimate the Alkire-Foster multidimensional poverty measure. It seems to be a very interesting approach.

Stata already has (at least) one implementation for complex surveys using complex survey design:
[Presentation about the MPI package](http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf)
[Working paper](http://155.185.68.2/campusone/web_dep/CappPaper/Capp_p131.pdf)

More info: [OPHI website](http://www.ophi.org.uk/policy/alkire-foster-methodology/)

PS: we can read the .ado file.

**Comment by ajdamico** [comment]
mpi ado file stored here:  https://ideas.repec.org/c/boc/bocode/s458120.html

we should be able to download the nlsy88 data set described in that presentation pdf with

	only.study <- "NLSW"
	library(downloader)
	setwd( "C:/My Directory/NLS/" )
	source_url( "https://raw.githubusercontent.com/ajdamico/asdfree/master/National%20Longitudinal%20Surveys/download%20all%20microdata.R" , prompt = FALSE , echo = TRUE )

we can limit to 1988 interviews by subsetting to records with nonzero survey weights for `R11092.20`

**Comment by guilhermejacob** [comment]
check the `AF` function in the [`parsec` package](https://cran.r-project.org/web/packages/parsec/parsec.pdf)

**Comment by guilhermejacob** [comment]
@ajdamico, Stata has [MPI](http://fmwww.bc.edu/repec/bocode/m/mpi.ado), which implements the Alkire Foster method. The aforementioned `parsec` package works only for ordinal variables; MPI seems to overcome that.

**Comment by ajdamico** [comment]
@guilhermejacob so, narrowly defined, is the task for me is to replicate the statistics in this pdf using R instead of stata?  any page(s) of the PDF in particular?  http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf  what would be the most help for you?  that `.ado` file is too big for me to translate it without having some end goal :)  it's also huge, so i might need five or six weeks..  but i will do it!

**Comment by guilhermejacob** [comment]
@ajdamico, if you could get the deprivation matrix, it would be great. It means collecting the data matrix, defining the cutoffs for each variable (but considering their classes too) and applying the cuttoffs for each variable. I think I can carry on from there.

**Comment by ajdamico** [comment]
@guilhermejacob  is the deprivation matrix pdf page 10 here?  http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf#page=10

**Comment by guilhermejacob** [comment]
@ajdamico, nope. check page 7 [here](http://www3.qeh.ox.ac.uk/pdf/ophiwp/OPHIWP043.pdf). There you can see all relevant matrices

**Comment by DjalmaPessoa** [comment]
Guilherme,

I'd like to start learning about multivariate poverty. Which reference do
you recommend?

**Comment by guilhermejacob** [comment]
@DjalmaPessoa, that's great! I think the best book about this is [Multidimensional Poverty Measurement & Analysis](http://multidimensionalpoverty.org/) and I'm quite sure you can read the chapters online.
Other interesting references are: [Udaya Wagle](https://www.amazon.com.br/Multidimensional-Poverty-Measurement-Concepts-Applications/dp/1441926097/ref=sr_1_5?ie=UTF8&qid=1480340514&sr=8-5&keywords=multidimensional+poverty) and [Kakwani & Silber](https://www.amazon.com.br/Quantitative-Approaches-Multidimensional-Poverty-Measurement/dp/023000489X/ref=sr_1_8?ie=UTF8&qid=1480340514&sr=8-8&keywords=multidimensional+poverty).
On multidimensional inequality, I suggest [Tsui](http://link.springer.com/article/10.1007/s003550050136) and [Abul Naga](https://ideas.repec.org/p/eid/wpaper/15976.html).
I can send you the pdfs.

**Comment by DjalmaPessoa** [comment]
How about a review paper?This  would  be more direct. The idea is to start working with you both in the convey new functions.

**Comment by guilhermejacob** [comment]
There isn't really a review paper, but there's this: [The Alkire-Foster Counting Methodology](http://multidimensionalpoverty.org/wp-content/uploads/chapter-5.pdf), [Data and Analysis](http://multidimensionalpoverty.org/wp-content/uploads/chapter-7.pdf) and, specially, [**Robustness Analysis and Statistical Inference**](http://multidimensionalpoverty.org/wp-content/uploads/chapter-8.pdf).

**Comment by DjalmaPessoa** [comment]
Thanks

**Comment by guilhermejacob** [comment]
On the calculation of standard errors for multidimensional poverty, there's this [Yalonetzky's lecture on video](http://www.ophi.org.uk/a-short-introduction-to-standard-errors-computations-for-af-measures). It provides a good idea of how it works, even discussing complex surveys.

**Comment by guilhermejacob** [comment]
https://github.com/DjalmaPessoa/convey/commit/8da8582b20b248678cb9af6eb58a7ffcb943c555 added the Alkire-Foster measure!
Using it, I was able to replicate the results from [Jindra's presentation](http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf#page=9), for both point and SE estimates. Since the measure is a actually a mean, there shouldn't be any problem on other survey designs.
I'll build this with @ajdamico as an example in another issue.

**Comment by ajdamico** [comment]
this is great, thanks @guilhermejacob .  @DjalmaPessoa we intend to replicate two scripts with `svyafc` (links below) but is there anything else you would like to check ?  please close this issue if you are satisfied..

https://github.com/DjalmaPessoa/convey/issues/155
https://github.com/DjalmaPessoa/convey/issues/154

**Comment by ajdamico** [comment]
i might use this to inform section 6.1 and 6.1.1
