### ISSUE TITLE
create a replication vignette for svyafc and svyafcdec

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#154]
Since the `eusilc` dataset isn't really useful for multidimensional poverty, I think it is easier and more meaningful to use another example.
My suggestion is replicating [Jindra's presentation](http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf#page=9):
```
library(foreign)

nlsw <- read.dta( "~/nlsw88.dta")
nlsw$psu <- 1
nlsw$collgrad <- ordered( nlsw$collgrad )
nlsw$hours <- as.numeric( nlsw$hours )

library(survey)
library(convey)

# linearized design
des_nlsw <- svydesign( ids = ~1 , data = nlsw )
des_nlsw <- convey_prep(des_nlsw)

# replicate-weighted design
des_nlsw_rep <- as.svrepdesign( des_nlsw , type = "bootstrap" )
des_nlsw_rep <- convey_prep(des_nlsw_rep)


# variable with missing values
svyafc(~wage+collgrad+hours, design = des_nlsw, cutoffs = list( 4, "college grad", 26), k = 1/3, g = 0, na.rm = T )
svyafc(~wage+collgrad+hours, design = des_nlsw_rep, cutoffs = list( 4, "college grad", 26), k = 1/3, g = 0, na.rm = T )

svyafc(~wage+collgrad+hours, design = des_nlsw, cutoffs = list( 4, "college grad", 26), k = 1/3, g = 1, na.rm = T )
svyafc(~wage+collgrad+hours, design = des_nlsw_rep, cutoffs = list( 4, "college grad", 26), k = 1/3, g = 1, na.rm = T )


svyafc(~wage+collgrad+hours, design = des_nlsw, cutoffs = list( 4, "college grad", 26), k = 1/3, g = 2, na.rm = T )
svyafc(~wage+collgrad+hours, design = des_nlsw_rep, cutoffs = list( 4, "college grad", 26), k = 1/3, g = 2, na.rm = T )


# variable with missing values
svyafc(~wage+collgrad+hours, design = des_nlsw, cutoffs = list( 4, "college grad", 26), k = .4, g = 0, na.rm = T )
svyafc(~wage+collgrad+hours, design = des_nlsw_rep, cutoffs = list( 4, "college grad", 26), k = .4, g = 0, na.rm = T )


# variable with missing values
svyafc(~wage+collgrad+hours, design = des_nlsw, cutoffs = list( 4, "college grad", 26), k = 1, g = 0, na.rm = T )
svyafc(~wage+collgrad+hours, design = des_nlsw_rep, cutoffs = list( 4, "college grad", 26), k = 1, g = 0, na.rm = T )
```

**Comment by ajdamico** [comment]
that sounds like a great plan.  could you troubleshoot this error?  i believe that missings are not being removed properly..  thanks

	devtools::install_github("djalmapessoa/convey")

	library(survey)
	library(convey)
	library(webuse)


	webuse("nlsw88")

	nlsw88 <- data.frame( nlsw88 )

	nlsw88$psu <- 1
	nlsw88$collgrad <- ordered( nlsw88$collgrad )
	nlsw88$hours <- as.numeric( nlsw88$hours )


	# linearized design
	des_nlsw88 <- svydesign( ids = ~1 , data = nlsw88 )
	des_nlsw88 <- convey_prep(des_nlsw88)

	# replicate-weighted design
	des_nlsw88_rep <- as.svrepdesign( des_nlsw88 , type = "bootstrap" )
	des_nlsw88_rep <- convey_prep(des_nlsw88_rep)


	svyafc(~wage+collgrad+hours, design = des_nlsw88, cutoffs = list( 4, "college grad", 26), k = 1/3, g = 0, na.rm = T )
	# Error in `[<-.data.frame`(`*tmp*`, multi.cut == 0, , value = 0) : 
	  # missing values are not allowed in subscripted assignments of data frames
	svyafc(~wage+collgrad+hours, design = des_nlsw88_rep, cutoffs = list( 4, "college grad", 26), k = 1/3, g = 0, na.rm = T )
	# Error in `[<-.data.frame`(`*tmp*`, multi.cut == 0, , value = 0) : 
	  # missing values are not allowed in subscripted assignments of data frames

**Comment by guilhermejacob** [comment]
when you do `nlsw88$collgrad <- ordered( nlsw88$collgrad )`, it "unlabels" things. So you would have to change the cutoffs to: `cutoffs = list( 4, 1, 26)`.
It's an issue with the 'labelled' class.

**Comment by ajdamico** [comment]
perfect.  so this code replicates some of the numbers on pdf pages 9 and 10.. but what other numbers in that pdf should be reproducible?  thanks

	library(survey)
	library(convey)
	library(webuse)


	webuse("nlsw88")

	nlsw88 <- data.frame( nlsw88 )

	nlsw88$collgrad <- factor( as.numeric( nlsw88$collgrad ) , label = c( 'not college grad' , 'college grad' ) , ordered = TRUE )
	nlsw88$psu <- 1

	# linearized design
	des_nlsw88 <- svydesign( ids = ~1 , data = nlsw88 )
	des_nlsw88 <- convey_prep(des_nlsw88)



	# replicate pdf page 9
	svyafc(~wage+collgrad+hours, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = 1/3, g = 0, na.rm = T )


	for( ks in seq(0.1,1,.1)){
		# replicate pdf page 10
		print(svyafc(~wage+collgrad+hours, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = ks , g = 0, na.rm = T ))
	}

**Comment by guilhermejacob** [comment]
Well, I can add H and A soon, but they would only appear in case `g=0`. I have to read a but more about it.
The `g` parameter variations can also be added, as in page 16:
```
for( gs in 0:3){
  # replicate pdf page 16
  print(svyafc(~wage+collgrad+hours, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = 1/3 , g = gs, na.rm = T ))
}
```

**Comment by ajdamico** [comment]
result <- svyafc(~wage+collgrad+hours, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = 1/3 , g = 0, na.rm = T )

	attr( result, "extra" )

	this will get you H and A if g = 0

**Comment by ajdamico** [comment]
also replicate pdf page 21 with

    svyby(~wage+collgrad+hours, ~married,design = des_nlsw88, svyafc,cutoffs = list( 4, 'college grad' , 26), k = 1/3, g = 0, na.rm = T )

**Comment by ajdamico** [comment]
# replicate pdf pages 17 and 19
	# http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf#page=17

	svyafcdec(~wage+collgrad+hours, design = des_nlsw88, by.formula = ~married, cutoffs = list( 4, 'college grad' , 26), k = 1/3, g = 0, na.rm = T )

**Comment by guilhermejacob** [comment]
page 17
```
# replicate pdf 17
svyafc(~wage+collgrad+hours, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = 1/3, g = 0, na.rm = T )
attr( svyafc(~wage+collgrad+hours, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = 1/3, g = 0, na.rm = T ), "extra")
svyafcdec(~wage+collgrad+hours, by = ~1, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = 1/3, g = 0, na.rm = T )[2]
```
page 19
```
# replicate pdf 19
# http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf#page=17

# Censored headcount ratios
for( ks in seq(1/3,1,1/3)){
  print ( svyafcdec(~wage+collgrad+hours, by = ~1, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = ks, g = 0, na.rm = T )[3] )
}
# Percentage contribution by dimensions
for( ks in seq(1/3,1,1/3)){
  print ( svyafcdec(~wage+collgrad+hours, by = ~1, design = des_nlsw88, cutoffs = list( 4, 'college grad' , 26), k = ks, g = 0, na.rm = T )[4] )
}
```

**Comment by ajdamico** [comment]
this is mostly done..  @guilhermejacob could you add code to replicate PDF page 22?  thanks

http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf#page=22

**Comment by ajdamico** [comment]
this is done

**Comment by guilhermejacob** [comment]
Here it is:
```
# replicate pdf page 22
for( ks in seq(1/3,1,1/3)){
  print( svyafcdec( ~wage+collgrad+hours, 
                    subgroup = ~factor(married), 
                    design = des_nlsw88, 
                    cutoffs = list( 4, 'college grad' , 26), 
                    k = ks , 
                    g = 0, 
                    dimw = NULL,
                    na.rm = T )[6])
}
```

There's a catch in the presentation: the last one, when `k = 1`, doesn't make sense. All others sum up to 100, which makes sense for a percentage. All of ours sum up to `1`.

Might be some rounding issue on the presentation.
