### ISSUE TITLE
Replicate UNDP's Multidimensional Poverty Index estimates for PNAD 2013

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#155]
The [MPI Statistical Programmes page](http://hdr.undp.org/en/content/mpi-statistical-programmes) provides the [Stata script to reproduce the Brazil's MPI using PNAD 2013](http://hdr.undp.org/sites/default/files/brazil_2013_pnad_mpi2_13_oct_2014.do).
Since the method is apparently the same, it shouldn't be (very) difficult to reprocude the estimates presented in [this report](http://hdr.undp.org/sites/all/themes/hdr_theme/country-notes/BRA.pdf#page=7).

**Comment by guilhermejacob** [comment]
made pointless by c87cde0d66823191c0e050158d0820024a955232

**Comment by ajdamico** [comment]
still a neat idea

**Comment by ajdamico** [comment]
https://hdr.undp.org/sites/default/files/MPI/congo_2014-15.r

https://hdr.undp.org/mpi-statistical-programmes

**Comment by ajdamico** [comment]
@guilhermejacob is this related to the IBGE measure released in 2023?
