### ISSUE TITLE
add a plot method for cdf from svyafc results

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#164]
Since commit e4e5a53b172f486be9d52348b91407b66fe14cbb, `svyafc` has attribute `"cdf"`, which returns the (`dimw` and `g`-) weighted deprivation sums.
Using this, we can replicate [this graph](http://www.ophi.org.uk/wp-content/uploads/OPHI-HDCA-SS11-Alkire-Foster-Multidimensional-Poverty-Measure.pdf#page=82).

**Comment by guilhermejacob** [comment]
This graph doesn't need the `cdf`.

**Comment by guilhermejacob** [comment]
Maybe [this](http://www.ophi.org.uk/wp-content/uploads/3-SS14-Pop-Decomp-and-Dim-Breakdown_SS.pdf#page=51).
Is it feasible, @ajdamico ?

**Comment by guilhermejacob** [comment]
we don't have the necessary information in svyafcdec yet. I think this should be postponed, since i have to add sub-dimensional decomposition in svyafc and svyafcdec

**Comment by ajdamico** [comment]
i don't really understand your end goal here (no problem), postponing seems fine, thanks

**Comment by guilhermejacob** [comment]
closed by c87cde0d66823191c0e050158d0820024a955232
