### ISSUE TITLE
why does svyafc not match jindra's presentation?

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#168]
# load the convey package
	library(convey)

	# load the survey library
	library(survey)

	# load the stata-style webuse library
	library(webuse)

	# load the same microdata set used by Jindra in his presentation
	webuse("nlsw88")

	# coerce that `tbl_df` to a standard R `data.frame`
	nlsw88 <- data.frame( nlsw88 )

	# create a `collgrad` column
	nlsw88$collgrad <-
		factor( 
			as.numeric( nlsw88$collgrad ) , 
			label = c( 'not college grad' , 'college grad' ) , 
			ordered = TRUE 
		  )

	# initiate a linearized survey design object
	des_nlsw88 <- svydesign( ids = ~1 , data = nlsw88 )

	# immediately run the `convey_prep` function on the survey design
	des_nlsw88 <- convey_prep(des_nlsw88)

	# these calculations match pdf page 13
	# http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf#page=13
	svyafc(
		~ wage + collgrad + hours , 
		design = des_nlsw88 , 
		cutoffs = list( 4, 'college grad' , 26 ) , 
		k = 0.75 , 
		g = 0 , 
		dimw = c( 0.5 , 0.25 , 0.25 ) ,
		na.rm = TRUE
	)

	svyafc(
		~ wage + collgrad + hours , 
		design = des_nlsw88 , 
		cutoffs = list( 4, 'college grad' , 26 ) , 
		k = 1 , 
		g = 0 , 
		dimw = c( 0.5 , 0.25 , 0.25 ) ,
		na.rm = TRUE
	)

	# why does this number not match the 0.5 from pdf page 13?
	# http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf#page=13
	svyafc(
		~ wage + collgrad + hours , 
		design = des_nlsw88 , 
		cutoffs = list( 4, 'college grad' , 26 ) , 
		k = 0.5 , 
		g = 0 , 
		dimw = c( 0.5 , 0.25 , 0.25 ) ,
		na.rm = TRUE
	)

**Comment by guilhermejacob** [comment]
can you run this in stata?

**Comment by ajdamico** [comment]
[20161210 reproduce slides 9 and 13.txt](https://github.com/DjalmaPessoa/convey/files/643753/20161210.reproduce.slides.9.and.13.txt)

is this what you need?

**Comment by guilhermejacob** [comment]
the functions had dome incorrect matrix operations, but the last commits fixed them.

So try this:
```
# these calculations match pdf page 13
# http://www.ophi.org.uk/wp-content/uploads/Jindra_151109_OPHISeminar.pdf#page=13
svyafc(
  ~ wage + collgrad + hours , 
  design = des_nlsw88 , 
  cutoffs = list( 4, 'college grad' , 26 ) , 
  k = 0.5 , 
  g = 0 , 
  dimw = c( 0.5 , 0.25 , 0.25 ) ,
  na.rm = TRUE
)

svyafc(
  ~ wage + collgrad + hours , 
  design = des_nlsw88 , 
  cutoffs = list( 4, 'college grad' , 26 ) , 
  k = 0.75 , 
  g = 0 , 
  dimw = c( 0.5 , 0.25 , 0.25 ) ,
  na.rm = TRUE
)

svyafc(
  ~ wage + collgrad + hours , 
  design = des_nlsw88 , 
  cutoffs = list( 4, 'college grad' , 26 ) , 
  k = 1 , 
  g = 0 , 
  dimw = c( 0.5 , 0.25 , 0.25 ) ,
  na.rm = TRUE
)
```
Closing it!

**Comment by ajdamico** [comment]
thanks!

**Comment by ajdamico** [comment]
also might be useful for me to show in 6.1
