### ISSUE TITLE
are any inequality measures appropriate for non-income?

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#181]
for example, assets?

or something more complicated like healthcare inequality?

cx @DjalmaPessoa  @guilhermejacob

**Comment by guilhermejacob** [comment]
Unless you create a variable with scores for each level (i.e., using a utility function), no measure in the package (so far) would really work.
Yet, there are some articles about it: [Cowell and Flachaire (2014)](http://darp.lse.ac.uk/pdf/IneqOrdinal.pdf), [Madden (2008)](https://www.york.ac.uk/media/economics/documents/herc/wp/08_09.pdf) and [Kobus (2012)](http://coin.wne.uw.edu.pl/mkobus/On%20the%20measurement%20of%20inequality%20for%20ordinal%20data.pdf), for instance.

**Comment by guilhermejacob** [comment]
[Talih (2015)](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4641042/) uses Rényi index to estimate healt inequality. I think we can try something like this.

**Comment by ajdamico** [comment]
doesn't seem like a priority, but my work would personally benefit from a
subchapter displaying how to compute this

**Comment by ajdamico** [comment]
https://www.theguardian.com/us-news/2017/apr/06/us-healthcare-wealth-income-inequality-lifespan

**Comment by ajdamico** [comment]
probably out of scope for the project but re-open if you strongly disagree?
