### ISSUE TITLE
create a replication vignette for svybmi

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#193]

**Comment by guilhermejacob** [comment]
@ajdamico , i don't this [Seth presentation example](http://www.ophi.org.uk/wp-content/uploads/Multidimensional-Inequality_SS.pdf#page=52) is much of a help, but it is a start.

**Comment by guilhermejacob** [comment]
043323bf3e1fc4af78e9a52e6f4b66daddf725d8 sets svybmi as experimental

**Comment by guilhermejacob** [comment]
closed by c87cde0d66823191c0e050158d0820024a955232
