### ISSUE TITLE
create a replication vignette for svyjdiv and svyjdivdec

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#194]

**Comment by guilhermejacob** [comment]
I could replicate [this](http://onlinelibrary.wiley.com/doi/10.1111/rssa.12153/abstract) if granted access to [the dataset](https://cnef.ehe.osu.edu/).

For now, all I can do is prove that it is the sum of Theil-L and Theil-T (two `svygei` indices).
Is that ok, @ajdamico ?

**Comment by ajdamico** [comment]
i can't see the article..does it have numbers generated with PSID?  that one is part of `lodown`..  it would be better if you could replicate the final results.  if PSID isn't an option, are there any other publications we could match?

**Comment by guilhermejacob** [comment]
I just recalled that Djalma showed me where to find the dataset: http://onlinelibrary.wiley.com/journal/10.1111/(ISSN)1467-985X/homepage/179_3.htm.
Working on it!

**Comment by ajdamico** [comment]
yes, so can't we just match the US numbers in the tables?  pdf page 9 of https://cnef.ehe.osu.edu/data/access-procedures/ says to access PSID from icpsr.  use `lodown( "psid" , output_dir = tempdir() )`  for registration instructions.  it's quick and easy :)

**Comment by ajdamico** [comment]
actually, i think you want this:  http://simba.isr.umich.edu/U/ca.aspx   they should send a certificate which you can fwd to OSU for their version of the PSID extract?

**Comment by guilhermejacob** [comment]
I understand, but it seems that cnef has modifications in terms of international comparability.
This might mean that they applied some conversions to the income data, like transforming currency into PPP$.

Will check it though.

For now, I wrote this small example showing that the J-divergence is the sum of GEI(0) and GEI(1), even for decompositions. It builds on a previous replication script used in the `svygei` `context` chapter.
```
library(convey)
library(survey)
library(foreign)
tf <- tempfile()
download.file( "http://econpapers.repec.org/scripts/redir.pf?u=http%3A%2F%2Frepec.org%2Fnasug2006%2Fnasug2006_jenkins.zip;h=repec:boc:asug06:16" , tf , mode = 'wb' )
z <- unzip( tf , exdir = tempdir() )

x81 <- read.dta( grep( "ifs81" , z , value = TRUE ) )
x85 <- read.dta( grep( "ifs85" , z , value = TRUE ) )
x91 <- read.dta( grep( "ifs91" , z , value = TRUE ) )

x <- rbind( x81 , x85 , x91 )
y <- svydesign( ~ hrn , data = x , weights = ~ wgt )
z <- convey_prep( y )

z81 <- subset( z , year == 1981 )

coef( svygei( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) , epsilon = 0 ) )
coef( svygei( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) ) )
coef( svyjdiv( ~ eybhc0 , subset( z81 , eybhc0 > 0 ) ) )

coef( svygeidec( ~ eybhc0 , subgroup = ~ but , subset( z81 , eybhc0 > 0 ) , epsilon = 0 ) )
coef( svygeidec( ~ eybhc0 , subgroup = ~ but , subset( z81 , eybhc0 > 0 ) , epsilon = 1 ) )
coef( svygeidec( ~ eybhc0 , subgroup = ~ but , subset( z81 , eybhc0 > 0 ) , epsilon = 0 ) ) +
  coef( svygeidec( ~ eybhc0 , subgroup = ~ but , subset( z81 , eybhc0 > 0 ) , epsilon = 1 ) )

coef( svyjdivdec( ~ eybhc0 , subgroup = ~ but , subset( z81 , eybhc0 > 0 ) , epsilon = 0 ) )
```

**Comment by ajdamico** [comment]
that's great!  might be a good addition to the text.  don't tables 1 and 2 of the rohde paper show measures of variation?  if you are having trouble with translating the stata code to figure out the inflation factors, i can help untangle that.  it would be nice to match a measure of uncertainty, but maybe that's not possible here.

**Comment by guilhermejacob** [comment]
ba8a0157ad5c19289c77b1297e432cf9a778031e and 742d4ab7015f3159a897b2e6690a808e187ae0c8 set svyjdiv and svyjdivdec as experimental
