### ISSUE TITLE
add replication vignette for svybcc

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#205]

**Comment by guilhermejacob** [comment]
@ajdamico , how's your portuguese?

There's a [recent article](http://www.scielo.br/pdf/rec/v20n1/1415-9848-rec-20-01-00177.pdf) that estimates the Bourguignon-Chakravarty index for Bahia using PNAD. Seems possible. Let's do it?

They probably didn't use all sample design info, but we should try it.

**Comment by guilhermejacob** [comment]
30abfd43c87a824a24405373b74a73f3521a57a9 sets svybcc as experimental

**Comment by guilhermejacob** [comment]
closed by c87cde0d66823191c0e050158d0820024a955232
