### ISSUE TITLE
what class(es) of object should svyafcdec return?

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#222]
https://github.com/DjalmaPessoa/convey/blob/master/R/svyafcdec.R#L17 says `cvystat` but currently `svyafcdec` returns a `list`

this matters for https://github.com/DjalmaPessoa/convey/issues/160

if you do think there should be a plot method available, i recommend that you re-class the `rval`s for svydesign and svyrepdesign this way, so we can write a `plot.cvyafcdec <-` method?

    class( rval ) <- c( "cvyafcdec" , "list" )

**Comment by guilhermejacob** [comment]
closed by c87cde0d66823191c0e050158d0820024a955232
