### ISSUE TITLE
add statement offering consulting to context

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#225]
maybe we should add a visible statement near the front of the textbook that informs readers that we might be available for paid consulting work

**Comment by DjalmaPessoa** [comment]
I don't feel like working in paid consulting these days. This might imply a
workload that I'm not prepared to take.

I have been answering  questions about  convey usage from graduate students
working in their thesis. Usually simple questions, and for that  I don't
charge anything.

Of course this is up to you and Guilherme.

**Comment by guilhermejacob** [comment]
I'm ok with paid consulting, specially after I move in the second semester.

**Comment by ajdamico** [comment]
payment must be in feijoada and antartica
