### ISSUE TITLE
Equivalised Income

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#226]
migrated from https://github.com/guilhermejacob/context/issues/5

DjalmaPessoa commented on Dec 9, 2016

Many examples used in convey are based on equivalised income.from EUSILC data This gives different weights to the people in a Household. As far as I know, this is not used by the people at IBGE. It might be interesting to use that with brazilian data for the first time. I believe it is possible to do that with the available information.

guilhermejacob commented on Dec 9, 2016

Sure! Here's an OECD comment on equivalence scales, just to present other options.

https://www.oecd.org/eco/growth/OECD-Note-EquivalenceScales.pdf

**Comment by guilhermejacob** [comment]
This is more of an analysis kind of question. The analyst should be able to transform the income data to the equivalised income. It doesn't seem to be dealt by the package itself.
Every place has a definition for the equivalised income, so it is complicated. It can be shown as an example of transforming a variable, but this should probably be done outside the survey design object, anyway.

What do you think, @ajdamico ? Close this if you're ok with this answer.
