### ISSUE TITLE
wellbeing measures

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#227]
migrated from https://github.com/guilhermejacob/context/issues/11

guilhermejacob commented on Dec 19, 2016

I'm not sure about this title.
I would put something like "Other social indices".
And svyqsr is an inequality measure, so I guess i can move it to chapter 3.
What do you think?

ajdamico commented on Dec 19, 2016

no preference from me

guilhermejacob commented on Dec 19, 2016 • edited

maybe something like "auxiliary functions". That way, we can explain svyrmir, svyiqalpha, icdf, densfun, etc.
I actually could use knowing a bit more on icdf in other functions.

ajdamico commented on Feb 17

@DjalmaPessoa what do you think

DjalmaPessoa commented on Feb 17

svyrmir is already included in the section poverty measures.
The other mentioned functions are only auxiliary and not worth beeing presented in the book and were created just to avoid command repetition, but are not special in any way.

**Comment by guilhermejacob** [comment]
this has been solved, hasn't it?

**Comment by guilhermejacob** [comment]
This one should have been closed a while ago. But we should stick to univariate measures, anyway.
