### ISSUE TITLE
adds Lv et al. (2015) ordinal inequality measure

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#241]
See [Lv et al. (2015)](http://file.scirp.org/pdf/TEL_2017022814165332.pdf).
The dataset is the Swiss Health Survey 2002.

**Comment by ajdamico** [comment]
shs 2002 would be included in https://github.com/ajdamico/asdfree/issues/224

**Comment by guilhermejacob** [comment]
I have to get some consultancy hahahaha

2017-04-17 19:53 GMT-03:00 Anthony Damico <notifications@github.com>:

**Comment by DjalmaPessoa** [comment]
Lv et al. (2015) presents an application example for a sample with no mention to its sample design.
Also the theoretical results are derived without  mentioning the sample design or even units weights.
The health status considered in the example is in the PNS questionnaire.  Perhaps we should try compute it for the PNS by regions or by states.
