### ISSUE TITLE
create svyrich entry with replication vignette

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#245]
Should it be a chapter? It would be quite small (1 function with two types).

**Comment by ajdamico** [comment]
and replication vignette  ;)

**Comment by guilhermejacob** [comment]
aee08e55c095ff832c1501b99cad428bbc00a993 adds svyrich as experimental

**Comment by ajdamico** [comment]
solved by https://github.com/guilhermejacob/context/pull/23
