### ISSUE TITLE
review subset behaviour on DBIdesign when full design is not needed

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#253]
If the full design is not needed, try to keep only `1/design$prob > 0`.
The objective here is to change what happens inside each `svysomething.DBIsvydesign`.

**Comment by ajdamico** [comment]
hi, if the `full_design` is not needed, why would any part of it be kept?  thanks

**Comment by DjalmaPessoa** [comment]
Please,  check  PNAD convey examples before you delete condition. In these
examples, there is a filter for the age and for the zero incomes before any
convey measure is computed.
If I'm not mistaken,  there was some problem to estimate convey measures
for PNAD microdata using DBIdesign.
