### ISSUE TITLE
decomposition chapter 1 section 10

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#260]
@DjalmaPessoa guilherme has already added the section that you requested in https://github.com/DjalmaPessoa/convey/issues/256  could you please look it over and make any edits that you feel are appropriate?  here are some additional questions that you might want to consider answering in the text (though guilherme already discusses these).  it would probably be good if we included a definition of decomposition that doesn't have the word *decomposition* in it haha  ;)  thanks all

what is a decomposition?

what is the utility of a decomposition?

what is the interpretation of the result of a decomposition?

how do convey decomposition functions differ from their central functions?  like svygei vs svygeidec

**Comment by guilhermejacob** [comment]
There are more than one type of decomposition. I need to explain that, too.

**Comment by ajdamico** [comment]
related to shapley, but these seem like questions worth answering in the book..
