### ISSUE TITLE
Using influence functions to analyze measures

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#262]
[Van Kerm (2015)](http://www.stata.com/meeting/uk15/abstracts/materials/uk15_vankerm.pdf) presents 3 possible uses for influence functions:

1. Variance Estimation
2. Study the structure of summary statistics
3. RIF regression

The first point we already do, but the second is particularly interesting. It can show where in the distribution a measure is most sensitive.

See also [Essama-Nssah & Lambert (2011)](http://www.ecineq.org/milano/WP/ECINEQ2011-236.pdf).

**Comment by guilhermejacob** [comment]
This is more a `context` than a `convey` thing.
 I t would be nice to show examples on how to use this information.

Do you agree, @DjalmaPessoa ?

**Comment by DjalmaPessoa** [comment]
I saw the slides from Van Kem (2015).
The Influence functions plots shown there are useful in the context of robustness of estimators. The concept was proposed by Hampel for that.
In convey we are using influence functions to get variance estimators. 
Could you give any interesting interpretation of these plots in the area of poverty and income concentration (not for statisticians)?

**Comment by guilhermejacob** [comment]
They can be used to show interesting aspects of the measures.

For instance, in `context`, we argue that: FGT(0) doesn't account for the depth of poverty; FGT(1) does, but doesn't for the inequality among the poor; and that FGT(2) does account for the three aspects.

Putting that in a (very rough) plot:
![image](https://cloud.githubusercontent.com/assets/12241665/25707314/7c2437fa-30b9-11e7-944c-b8d248fb29e2.png)

This way, we can see that observations below the poverty line in FGT(0) are equally weighted, irrespective of whether they are $1 or $1000 below the poverty line. On the other hand FGT(1) and FGT(2) "influence" decrease as we approach the poverty line. The difference between FGT(1) and FGT(2) is the rate of decrease: while in FGT(1), the gap between income and poverty is linear, in FGT(2) the gap grows in a non-linear rate as income-poverty line gaps increase.

Also, we can use this kind of plot to argue why we should account for the variance in measures using relative poverty lines, as it would show that the non-poor influence the overall measure.

But you're the statistician! You tell me if that makes sense and if it is worth adding.

**Comment by DjalmaPessoa** [comment]
I believe it is worth adding as long as you can give  interesting subject matter interpretations, like the one  you just gave. 
Statisticians would be more interested in robustness questions like:
what happen to the mean, median or some estimator when we let one observation go to infinite?
This is not much relevant to convey.

**Comment by guilhermejacob** [comment]
@DjalmaPessoa , can I add a pointer to that kind of analysis in the Influence functions section?

**Comment by DjalmaPessoa** [comment]
I’m not sure I understand what you mean by a pointer.

Em 20 de nov de 2017, à(s) 17:35, Guilherme Jacob <notifications@github.com> escreveu:

**Comment by guilhermejacob** [comment]
Related to #242
