### ISSUE TITLE
guidance for users who do not know which to choose

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#263]
we ought to have a flowchart (like the asdfree one below, but serious) to help people choose a poverty measure.  which poverty measure is most appropriate for your analysis?  something like the https://choosealicense.com/ page.  what is the relative strength of each poverty measure, compared to all the others?

[1] https://github.com/ajdamico/asdfree/raw/master/analyze%20survey%20data%20for%20free%20-%20the%20flowchart.pdf

**Comment by guilhermejacob** [comment]
This is an interesting idea. Inequality measures and poverty measures should be treated different in that sense. I'd start by looking at the desirable axioms of each.

**Comment by guilhermejacob** [comment]
aae80f580c17ea771351b3a7650078231c2cde32 added a section on this for inequality measures. Introduced in inequality .rmd only.

**Comment by ajdamico** [comment]
i've reverted because this commit broke the build.  when you add it back in please build and debug the problem, thanks

**Comment by guilhermejacob** [comment]
I rewrote the commit and fixed the bugs. The pdf, pub and html are working locally. However, the online version is not. This is not limited to context, as it seems to be affecting my other websites on GitHub Pages.

**Comment by ajdamico** [comment]
[![](https://mermaid.ink/img/pako:eNrtWWtz2zYW_SsYTjuxZySN7cax19PHOH47zqOJ27Rd7weIvJJQkwQDgJIVO_99zwVAmpLstNvObD-0yTiRCfDi3HPPfcC-TVKdUbKXXJVjI6uJuDy8KvHX7f_7KjnUYq5rMZFTElKkuqhyuhFW8v_C1mZKc5GRVeNS6OGvlDqRGpKOMjFTbiII_5ARdjoPm9bWheZvDVXtg--ukv_wcf5I0e9_K-5e6TvxHKe_lf51N5Elzi5xWI__tyrzT0nkkq6pZJtTabJK48NbkauhkUaRXTX8M9k7cQDL73WdZ961XF2TcFpMla1lrj6SUCV94I9u3oV20LFwCAvwKdeGyo9woTJ6CkwWFFlnpBpP3EibGSAJT6lKhR6JiZ59PTTf4lAjKl3VuXRKl7yiSkeGrBOZGo3IWDEyuhAVmREz2qBZBcM8HQHLvqHgi9bXqhwLHM5QUuATa1YVKpeGfWTKxqpUIJFGI5UqKt06Y0JgC13mc1FbhG44ByI8IiY7xR4TkAIiSZMiJLbHbw1rx7FxomCPRamdGJIgaRVbKhEk67T29vzJVJKRuajqYa7SLrdHjTs9cSZKAgTrcKR1KrWMG9SmRg1Zgh3i6KaCHeVwGPZIiGEuZJ3BqZTuxHGHF7qRBdwGM5WeknFzVsxqmI_aEDMOWSzxyeo3NCHoD9lQwM8a9n34VslifmgKbaqRdz6VedoAl2UmlLMh7DDpwuPA4pD4VRaCwgvOn73KHnscGYa1O3GyqmkIANg5TRsuW1tAqUyTv2D7ntRIBcg4DmS8CYTdidMOn41e8aoqPS-1Y55ky6-bYH2i84ydWeNzOQYoGj0PoNmWIwhegEzwg8Y9dxNpZIqnQRF-_yjaadXg602uZ2RiPGwT1uDJ2e1ZG_BPjfBO_dL57WUD16-c-6cvQpJLUzmkeHASKc7Htt5x9CWfKnwckPARXK6mTEhkB9XIAmKTgTGScU_z5r1f2nIREr5QNDVWOmnJeTYhpRzksCnp-jB93dej_grz650EC35e3F4lB4tcXiUtFxd-z0t4_eQUDhWynPuYcAmGzKeMOf_uCUMItJhlWuxEhoRYDA2_EX0dEnP1W8gj8ADoVQMoC-xRDtUj5QOvvnQjz8xcl7xmqUVoCrWMkFd8ejLIgjKFvhKTV494sSLNjU0OAUlMbcSL1AdAiZDIMS2Ae92AGyoEO7AwllXPK5dMYfmgTOeov1asQeTaN7S0Nugc6Xy9A7YaL9NpiPkDkNAVuKz5qktuRhQyY9kHER3wuHnzb1HNe7gcLaoaxYny0YKnb1pd1OmkOTDTEWrEUdbFEO55BYCNBw4eG11XfpxoXeeujfeXvV90TaI9cTpl0FGGJLZ_VFT8deY9-j7k9_h3E39f6ZsQFBSK-QwPy3hAMP42GP9gV5Kk1V-0hY5ako9DbJNOV2Jr40toDYqzzj-7DzB_N9TOYT7ApqZa49wTf-47nBv710yW7qEmgISJueODH0-Jk5pPY1kwCsfNZiGJ19Dqg4CdwhbMJ0pn1o90jZmw_EBjaYaxAPMSMEO3n_mm1QxhhbymTsX0UebCrgLPXenbeujF1JTNYv7QsR2C3vmTf_jfxwL--sG__CMKaGyIncL5o197HyI-Grs1MRgMRE-MxTdiYyn6E5JZqmtEpjkSeiA_TTUDW13KEc99YRAbEvDx8hebjO6LzY2NjuC7fTSiDWh-ehDN5mo5lFzXx4ThzRR-_M1ao1zIfAAwv06EQ2j8yIJRKw0uMIJMcf9KqWluXUR7nZL6GeDxdsGbJxiByLSrgRA__vuuGHh4zM5A8DpqFPeDXuxbKENQfZ5DP4IgpJRVbfQwp2IvDFqP4-eXpf-E8XlUlykrasBvXXJ5wwRY2jAAY8hjQTFHApWK5rzJD_HBpvbTPUt4zHVFgTvdlOecrPVbxBpLXdd8h9LWxrivjEu95afNJNq62iTxgiJ-flARW48rwiINDOTwWWVQGBBixzQ0hqN-PMYYXFoUz5DBAIUFHmd9JnM9wzXRNhXN62TRm4E4K2M1mWkMR_68sSwK-c1W1OKT-1Rls9HAkwWNLlDwS6BgJp2z3bIsWwpD6ZFQhyc5SOL3EdKUKljj6th3uk83yrWNaHHY99rzA7ywXNnX6hKE5L5C9wRfrHATG9X5upDW1kXlS2gvCBYdkGsWQ3vPrrToUS46HbMswQ033BlAcZURb_31U2GCsguO3bftOZTuCypP7DnJabc4cgup7WClKu7voyzeD9edyrgfrt3Pn8dWi2K73A6Xr6OxFDYX0r6_kE5lXlP3IuhvV7hv6QINrSMDn4wz4osURq_a5Ypv0345b-7PEdTBQQRFqkkIqnBzxZyOsi1W8-JyQirvX_AQQje9jmgs3wj9vBCS-n5qsHFuCSP96g1lEdHh4WcQbT6K6PJPIoo190FIR0cB0q9Q3XLkzvt4SGbMZpuT2zGpiUgXVan9_YXVhPm9i7GdPqTKO_Jqvi49luPjP9a6j8P97-TkweZ9EgaS09O2PGaU_rUdPEA6O3sM0T9d_O_YxaNQz88fk8XfpJVHHl686DRzZuKffv7n-_lSyby4eKyxX8QfFr1sO1ZHjH9VG42gXr36PKj_byeNl8_Xr-NPE901_8qj6U9v3oTH6oPMq4nsLn0ffz6h7If7x0kvKQhqVVmyl9xelUJcJXCBi8QePmY0ksjMq-Sq_IStsnb63bxMkz1nauoldZVBNodKjo0skr2RzC2eUqacNi_D74D8r4J6SSXLX7QumhfxbbJ3m9wke_3Nna92B9v_era7sbmzvbO7ubXdS-bJ3tbGzmBrc-fp1tbT3e2vtje3n33qJR-9iaeD3acb-IP9z3Z3dzaffvov5vhpiA?type=png)](https://mermaid.live/edit#pako:eNrtWWtz2zYW_SsYTjuxZySN7cax19PHOH47zqOJ27Rd7weIvJJQkwQDgJIVO_99zwVAmpLstNvObD-0yTiRCfDi3HPPfcC-TVKdUbKXXJVjI6uJuDy8KvHX7f_7KjnUYq5rMZFTElKkuqhyuhFW8v_C1mZKc5GRVeNS6OGvlDqRGpKOMjFTbiII_5ARdjoPm9bWheZvDVXtg--ukv_wcf5I0e9_K-5e6TvxHKe_lf51N5Elzi5xWI__tyrzT0nkkq6pZJtTabJK48NbkauhkUaRXTX8M9k7cQDL73WdZ961XF2TcFpMla1lrj6SUCV94I9u3oV20LFwCAvwKdeGyo9woTJ6CkwWFFlnpBpP3EibGSAJT6lKhR6JiZ59PTTf4lAjKl3VuXRKl7yiSkeGrBOZGo3IWDEyuhAVmREz2qBZBcM8HQHLvqHgi9bXqhwLHM5QUuATa1YVKpeGfWTKxqpUIJFGI5UqKt06Y0JgC13mc1FbhG44ByI8IiY7xR4TkAIiSZMiJLbHbw1rx7FxomCPRamdGJIgaRVbKhEk67T29vzJVJKRuajqYa7SLrdHjTs9cSZKAgTrcKR1KrWMG9SmRg1Zgh3i6KaCHeVwGPZIiGEuZJ3BqZTuxHGHF7qRBdwGM5WeknFzVsxqmI_aEDMOWSzxyeo3NCHoD9lQwM8a9n34VslifmgKbaqRdz6VedoAl2UmlLMh7DDpwuPA4pD4VRaCwgvOn73KHnscGYa1O3GyqmkIANg5TRsuW1tAqUyTv2D7ntRIBcg4DmS8CYTdidMOn41e8aoqPS-1Y55ky6-bYH2i84ydWeNzOQYoGj0PoNmWIwhegEzwg8Y9dxNpZIqnQRF-_yjaadXg602uZ2RiPGwT1uDJ2e1ZG_BPjfBO_dL57WUD16-c-6cvQpJLUzmkeHASKc7Htt5x9CWfKnwckPARXK6mTEhkB9XIAmKTgTGScU_z5r1f2nIREr5QNDVWOmnJeTYhpRzksCnp-jB93dej_grz650EC35e3F4lB4tcXiUtFxd-z0t4_eQUDhWynPuYcAmGzKeMOf_uCUMItJhlWuxEhoRYDA2_EX0dEnP1W8gj8ADoVQMoC-xRDtUj5QOvvnQjz8xcl7xmqUVoCrWMkFd8ejLIgjKFvhKTV494sSLNjU0OAUlMbcSL1AdAiZDIMS2Ae92AGyoEO7AwllXPK5dMYfmgTOeov1asQeTaN7S0Nugc6Xy9A7YaL9NpiPkDkNAVuKz5qktuRhQyY9kHER3wuHnzb1HNe7gcLaoaxYny0YKnb1pd1OmkOTDTEWrEUdbFEO55BYCNBw4eG11XfpxoXeeujfeXvV90TaI9cTpl0FGGJLZ_VFT8deY9-j7k9_h3E39f6ZsQFBSK-QwPy3hAMP42GP9gV5Kk1V-0hY5ako9DbJNOV2Jr40toDYqzzj-7DzB_N9TOYT7ApqZa49wTf-47nBv710yW7qEmgISJueODH0-Jk5pPY1kwCsfNZiGJ19Dqg4CdwhbMJ0pn1o90jZmw_EBjaYaxAPMSMEO3n_mm1QxhhbymTsX0UebCrgLPXenbeujF1JTNYv7QsR2C3vmTf_jfxwL--sG__CMKaGyIncL5o197HyI-Grs1MRgMRE-MxTdiYyn6E5JZqmtEpjkSeiA_TTUDW13KEc99YRAbEvDx8hebjO6LzY2NjuC7fTSiDWh-ehDN5mo5lFzXx4ThzRR-_M1ao1zIfAAwv06EQ2j8yIJRKw0uMIJMcf9KqWluXUR7nZL6GeDxdsGbJxiByLSrgRA__vuuGHh4zM5A8DpqFPeDXuxbKENQfZ5DP4IgpJRVbfQwp2IvDFqP4-eXpf-E8XlUlykrasBvXXJ5wwRY2jAAY8hjQTFHApWK5rzJD_HBpvbTPUt4zHVFgTvdlOecrPVbxBpLXdd8h9LWxrivjEu95afNJNq62iTxgiJ-flARW48rwiINDOTwWWVQGBBixzQ0hqN-PMYYXFoUz5DBAIUFHmd9JnM9wzXRNhXN62TRm4E4K2M1mWkMR_68sSwK-c1W1OKT-1Rls9HAkwWNLlDwS6BgJp2z3bIsWwpD6ZFQhyc5SOL3EdKUKljj6th3uk83yrWNaHHY99rzA7ywXNnX6hKE5L5C9wRfrHATG9X5upDW1kXlS2gvCBYdkGsWQ3vPrrToUS46HbMswQ033BlAcZURb_31U2GCsguO3bftOZTuCypP7DnJabc4cgup7WClKu7voyzeD9edyrgfrt3Pn8dWi2K73A6Xr6OxFDYX0r6_kE5lXlP3IuhvV7hv6QINrSMDn4wz4osURq_a5Ypv0345b-7PEdTBQQRFqkkIqnBzxZyOsi1W8-JyQirvX_AQQje9jmgs3wj9vBCS-n5qsHFuCSP96g1lEdHh4WcQbT6K6PJPIoo190FIR0cB0q9Q3XLkzvt4SGbMZpuT2zGpiUgXVan9_YXVhPm9i7GdPqTKO_Jqvi49luPjP9a6j8P97-TkweZ9EgaS09O2PGaU_rUdPEA6O3sM0T9d_O_YxaNQz88fk8XfpJVHHl686DRzZuKffv7n-_lSyby4eKyxX8QfFr1sO1ZHjH9VG42gXr36PKj_byeNl8_Xr-NPE901_8qj6U9v3oTH6oPMq4nsLn0ffz6h7If7x0kvKQhqVVmyl9xelUJcJXCBi8QePmY0ksjMq-Sq_IStsnb63bxMkz1nauoldZVBNodKjo0skr2RzC2eUqacNi_D74D8r4J6SSXLX7QumhfxbbJ3m9wke_3Nna92B9v_era7sbmzvbO7ubXdS-bJ3tbGzmBrc-fp1tbT3e2vtje3n33qJR-9iaeD3acb-IP9z3Z3dzaffvov5vhpiA)

**Comment by ajdamico** [comment]
[draft flowchart.txt](https://github.com/ajdamico/convey/files/10306999/draft.flowchart.txt)

this file pastes into the open source flowchart generator at https://mermaid.live/

**Comment by ajdamico** [comment]
how and where do these four functions fit into this flowchart?

`svyatk`
`svyrich`
`svyiqalpha`
`svyisq`

**Comment by ajdamico** [comment]
from G

[9/13, 11:42 AM] Guilherme Jacob: AA --> FF["svyatk() computes the Atkinson index, an inequality measure with a direct link to social welfare functions"]
[9/13, 11:47 AM] Guilherme Jacob: i think it is an option among inequality measures. Wherever svygei can be used, so can svyatk. The difference is that one is an Entropy based measure (a kind of statistical concept), while the other has a clearer link to a (hypothethized) social welfare function, which might make it more interpretable to economists.
[9/13, 11:51 AM] Guilherme Jacob: GE indices are more common. I would point them, them point to Atkinson if they want something that can be interpreted int terms of a social welfare function.

**Comment by ajdamico** [comment]
Imagine that there is a function that assigns a welfare/happiness/satisfaction value to a given amount of money.

The marginal utility of money is the crucial part for SWF-based inequality measurement. It expresses the idea that more money gives more welfare, but at a diminishing rate. So $100 makes less difference in someone’s welfare as we move along the income distribution.
