### ISSUE TITLE
try extending convey functions to work with srvyr

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#267]
https://github.com/gergness/srvyr/blob/master/vignettes/extending-srvyr.Rmd

**Comment by ajdamico** [comment]
add to `SUGGESTS:`  srvyr

**Comment by DjalmaPessoa** [comment]
Question: in order to get the Example convey::svyarpr -> survey_arpr in https://github.com/gergness/srvyr/blob/master/vignettes/extending-srvyr.Rmd I just need to replace "gini" by "arpr" all over?

**Comment by DjalmaPessoa** [comment]
the script in https://github.com/gergness/srvyr/blob/master/vignettes/extending-srvyr.Rmd doesn't work for all the functions in convey. It fails for functions that effectively use the full.design attribute. This can be easily fixed in order to make it work for all the functions.

**Comment by DjalmaPessoa** [comment]
R scripts to implement convey functions with srvyr are in https://github.com/DjalmaPessoa/convey/tree/master/scripts

**Comment by ajdamico** [comment]
moved scripts here (since they cannot be part of built package in their current form)

[extending-svryr1.txt](https://github.com/DjalmaPessoa/convey/files/4658409/extending-svryr1.txt)
[wrapper_fun.txt](https://github.com/DjalmaPessoa/convey/files/4658410/wrapper_fun.txt)
