### ISSUE TITLE
Building vignettes and adding pkgdown site

### ISSUE THREAD

**Issue by Edouard-Legoupil** [ajdamico/convey#271]
Hi - Discovering your package today - Amazing work!!!

Why not converting your [book on poverty and inequality measurement using complex survey samples, based on `convey` package.](https://github.com/guilhermejacob/context) into vignettes within your package - and then displaying the content with 
```
library("pkgdown")
pkgdown::build_site()
```
Just an idea - but I feel it would be more user friendly to have all those doc through vinettes.

**Comment by ajdamico** [comment]
thanks

**Comment by ajdamico** [comment]
@guilhermejacob were you referring to this in your write-up?

**Comment by Edouard-Legoupil** [comment]
Hello - just sent https://github.com/ajdamico/convey/pull/363 - pkgdown creates convenient doc..
