### ISSUE TITLE
Remove multidimensional measures

### ISSUE THREAD

**Issue by guilhermejacob** [ajdamico/convey#272]
Edit functions and book.

**Comment by guilhermejacob** [comment]
We better stick to univariate measures. The convey package user interface isn't well suited for multidimensional measures.

**Comment by ajdamico** [comment]
wait, i'm confused?  which are the multi-dimensional measures?  do you have a git commit where they're removed from both the package and the book?

**Comment by ajdamico** [comment]
https://guilhermejacob.github.io/context/4-multidimensional.html#multidimensional
