### ISSUE TITLE
polarization text edit

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#387]
so like this?  can you give the one more mini-explanation?  this is the only place in the text we use the word "polarization"

The reasoning behind the concave transfer axiom is that such progressive transfer would make the income distribution among the rich more internally homogeneous, "clustering" their incomes and interests. On the other hand, convex richness measures are more sensitive to the inequality among the rich. In a sense, concave measures are related to the income polarization approach, meaning that *[something here?]*.  On the other hand, convex measures are related to the income inequality approach, meaning that if a billionaire gave money to a millionaire, inequality among the rich is reduced and so should a convex richness measure.

**Comment by guilhermejacob** [comment]
Another try:

The reasoning behind the concave transfer axiom is that such progressive transfer would make the income distribution among the rich more internally homogeneous. By "clustering" the incomes and interests of the rich away from the rest of society, the distribution of income becomes more polarized. On the other hand, the convex transfer axiom means that a progressive transfer among rich individuals reduces inequality among them, so the convex inequality measure should register a reduction. In a sense, concave measures are related to the income polarization approach, meaning that increases in income polarization should increase the value of the richness measure, while convex measures are related to the income inequality approach, meaning that a reduction in inequality among the rich should also result in a reduction of a convex richness measure.

**Comment by ajdamico** [comment]
@guilhermejacob i changed "interests" to "assets"  -- is that OK?
