### ISSUE TITLE
proposed revision to context structure

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#419]
i'd like to re-organize the book a bit, could you please compare `current structure` with `proposed revision` and tell me if you'd be OK with me making this change or if you would like it done differently? --

current structure:

	# Introduction
	## Installation {#install}
	## Complex surveys and statistical inference {#survey}
	## Usage Examples
	## Underlying Calculations {#lin}
	## The Variance Estimator {#var}
	## Influence Functions
	## Influence Function Examples
	## Examples of Linearization Using the Influence Function
	## Replication Designs
	## Decomposition

	# Poverty Indices {#poverty}
	## At Risk of Poverty Threshold (svyarpt)
	## At Risk of Poverty Ratio (svyarpr)
	## Relative Median Income Ratio (svyrmir)
	## Relative Median Poverty Gap (svyrmpg)
	## Median Income Below the At Risk of Poverty Threshold  (svypoormed)
	## Foster-Greer-Thorbecke class (svyfgt, svyfgtdec)
	## Watts poverty measure (svywatts, svywattsdec)

	# Inequality Measurement {#inequality}
	## The Gender Pay Gap (svygpg)
	## Quintile Share Ratio (svyqsr)
	## Lorenz Curve (svylorenz)
	## Gini index (svygini)
	## Zenga index (svyzenga)
	## Entropy-based Measures
	## Generalized Entropy and Decomposition (svygei, svygeidec)
	## J-Divergence and Decomposition (svyjdiv, svyjdivdec)
	## Atkinson index (svyatk)
	## Which inequality measure should be used?

	# Richness Measures
	

proposed revision:

	# Introduction
	## Installation {#install}
	## Complex surveys and statistical inference {#survey}
	## Replication Designs
	## Usage Examples

	# Underlying Calculations {#lin}
	## The Variance Estimator {#var}
	## Influence Functions
	## Influence Function Examples
	## Linearization
	### Linearization Examples Using the Influence Function
	## Decomposition
	### Decomposition Example

	# Poverty {#poverty}
	## At Risk of Poverty Threshold (svyarpt)
	### Replication Example
	## At Risk of Poverty Ratio (svyarpr)
	### Replication Example
	## Relative Median Income Ratio (svyrmir)
	### Replication Example
	## Relative Median Poverty Gap (svyrmpg)
	### Replication Example
	## Median Income Below the At Risk of Poverty Threshold  (svypoormed)
	### Replication Example
	## Foster-Greer-Thorbecke class (svyfgt, svyfgtdec)
	### Replication Example
	### Monte Carlo Simulation
	## Watts poverty measure (svywatts, svywattsdec)
	### Monte Carlo Simulation
	
	# Inequality {#inequality}
	## Which inequality measure should be used?
	## Gender Pay Gap (svygpg)
	### Replication Example
	## Quintile Share Ratio (svyqsr)
	### Replication Example
	## Lorenz Curve-based Measures
	## Lorenz Curve (svylorenz)
	### Replication Example
	## Gini index (svygini)
	### Replication Example
	## Zenga index (svyzenga)
	### Replication Example
	## Social Welfare Function-based Measures
	## Atkinson index (svyatk)
	### Replication Example
	## Entropy-based Measures
	## Generalized Entropy and Decomposition (svygei, svygeidec)
	### Replication Example
	## J-Divergence and Decomposition (svyjdiv, svyjdivdec)
	### Monte Carlo Simulation

	# Richness {#richness}
	## Richness Measures (svyrich)
	### Monte Carlo Simulation

	# Future Research
	## Multidimensional Poverty
	### Example Calculation
	## Covariance Matrix
	### Example Calculation

**Comment by guilhermejacob** [comment]
Suggested changes:

```
# Introduction
## Installation {#install}
## Complex surveys and statistical inference {#survey}
## Variance Estimation: Linearization and Replication-Based Methods 
## Usage Examples

# Underlying Calculations for Linearization-Based Variance Estimation {#lin}
## The Variance Estimator {#var}
## Influence Functions
## Influence Function Examples
## Linearization
### Linearization Examples Using the Influence Function
## Decomposition
### Decomposition Example
```
