### ISSUE TITLE
do any stale branches have code that still ought to be incorporated or saved?

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#420]
not sure if we can delete all of these stale branches, or if we want to keep any of the information in these proposed changes?

https://github.com/ajdamico/convey/branches

**Comment by guilhermejacob** [comment]
i went through them. We can drop all stale branches. I can do that -- just let me know.
I'd keep branch `issue-372` for reproducibility purposes. If you could find a way to close it to new changes without deleting it, that would be great.
