### ISSUE TITLE
please proofread chapter 2

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#446]
https://guilhermejacob.github.io/context/2-var.html#var

it's great!  minor things that came to mind--

section 2.2 has a lot of R code, which i think helps readers get the gist of the calculation.  do you think there are any places in sections 2.1 and 2.3 where you could add snippets of R code that might help some readers understand what's happening under the hood a little better?  

does it make sense to add a bit more explanatory text to sections 2.1.1.1 and 2.1.1.2 ?

thaaaanks

**Comment by guilhermejacob** [comment]
I think that, at this point of the text, this would only complicate things further. If ste-by-step code for how to implement variance estimation using influence functions is actually needed, I'd put it in some sort of appendix. Notice that Lumley did kind of the same thing in his book.

**Comment by ajdamico** [comment]
thank you!
