### ISSUE TITLE
edit announcement for SRMSNET / potential conference abstract

### ISSUE THREAD

**Issue by ajdamico** [ajdamico/convey#456]
subject line: the R convey package: Poverty and Inequality with Complex Survey Data

We are excited to release a major update of our free and open-source R `convey` package, accompanied by an obsessively-detailed textbook that presents usage examples from major population surveys of both Brazil and the United States.  We feel this project now provides a comprehensive toolkit for the measurement of poverty and inequality with complex sample survey data.

The software can be downloaded like any other R package:  https://cran.r-project.org/web/packages/convey/index.html

The textbook and introductory flowchart live at https://guilhermejacob.github.io/context/

We hope that our work allows researchers explore the topics of poverty and inequality in greater depth, and we invite your suggestions!

**Comment by guilhermejacob** [comment]
subject line: the R convey package: Poverty and Inequality with Complex Survey Data

We are excited to release a major update of our free and open-source R convey package, accompanied by an detailed textbook that presents usage examples from major population surveys of both Brazil and the United States, including examples that reproduce published estimates by official statistical offices. We feel this project now provides a comprehensive toolkit for the measurement of poverty and inequality with complex sample survey data.

The software can be downloaded like any other R package: https://cran.r-project.org/web/packages/convey/index.html

The textbook and introductory flowchart live at https://guilhermejacob.github.io/context/

We hope that our work allows researchers explore the topics of poverty and inequality in greater depth, and we invite your suggestions!

**Comment by ajdamico** [comment]
scheduled for wednesday morning!
